name: Build release

on: [ push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cargo build
        run: cargo build --verbose
      - name: Build debug
        run: bash ./script/build.sh
      - name: Build release
        run: bash ./script/build.sh --release
  test:
    runs-on: ubuntu-latest
    needs: [ build ]
    steps:
      - uses: actions/checkout@v2
      - name: Cargo test
        run: cargo test --verbose
